apiVersion: v1
kind: Secret
metadata:
  name: chess-secret
  namespace: chess
type: Opaque
stringData:
  postgres-password: chess
  postgres-user: chess
  pgadmin-email: admin@chess.com
  pgadmin-password: admin
