apiVersion: v1
kind: Service
metadata:
  name: pgadmin
  namespace: chess
spec:
  type: NodePort
  selector:
    app: pgadmin
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30050
    name: http
